// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types';

const SUPABASE_URL = "https://zzcmxzyumveoyibxbamn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y214enl1bXZlb3lpYnhiYW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjI4MDEsImV4cCI6MjA3NDAzODgwMX0.GZdAHL0bgQOghJEHthwEx8f4xb3xnsR6z7a0rPHRIi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});